**TF Syntax Basics**

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


In [0]:
hello = tf.constant("Hello")

In [0]:
world = tf.constant("Wrold")

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [11]:
print(result)

b'HelloWrold'


In [0]:
a = tf.constant(10)

In [0]:
b = tf.constant(20)

In [16]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
  result = sess.run(a + b)

In [18]:
result

30

In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4), 10)

In [0]:
myzeros = tf.zeros((4,4))

In [0]:
myones = tf.ones((4,4))

In [0]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [0]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [25]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [0]:
my_ops = [const, fill_mat, myzeros, myones, myrandn,myrandu]

In [0]:
sess = tf.InteractiveSession()

In [32]:
for op in my_ops:
  print(sess.run(op))
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.1575713   0.23710245  1.661493   -0.7021214 ]
 [-0.08589701  0.18451549 -0.5731745   1.0920243 ]
 [-0.49312776  0.07344081 -1.6354026  -0.31344587]
 [-0.06411703 -0.02896505  0.44715104  0.97826225]]


[[0.16934729 0.49293268 0.5644306  0.3365686 ]
 [0.54619753 0.82681644 0.53990173 0.39054143]
 [0.61248934 0.04804409 0.76394224 0.53345156]
 [0.77725935 0.6457478  0.14837432 0.16005552]]




In [0]:
a = tf.constant([[1,2],
                [3,4]])

In [35]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10], [100]])

In [37]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [39]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [40]:
result.eval()

array([[210],
       [430]], dtype=int32)

**Great Job Shivan!**